name: Deploy main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Dependencies
        run: npm ci
        working-directory: frontend/app

#      - name: Install Test Dependencies
#        run: npm ci
#        working-directory: _integration-test-vitest

#      - name: Run Tests
#        run: npm run test
#        working-directory: _integration-test-vitest

      - name: Build
        run: npm run build
        working-directory: server

#      - name: Deploy to Server
#        if: success()
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#        run: |
#          mkdir -p ~/.ssh
#          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
#          chmod 600 ~/.ssh/id_rsa
#          ssh-keyscan -H code-collective.dci-web-dev.com >> ~/.ssh/known_hosts
#          rsync -avz --delete --no-times --no-perms ./server/dist/ ralf@code-collective.dci-web-dev.com:/var/www/students/ralf